### ISSUE TITLE
On OSMC

### ISSUE THREAD

**Issue by MrMjolnir** [fastoe/RTL8812BU_for_Raspbian#10]
Hi fastoe,

Just a comment: maybe you can add on the readme that it also works perfectly on OSMC. 
The only change is how to install the headers:
`apt-cache search osmc | grep headers`
gives you the exact version of headers to install, in my case rbp2-headers-5.10.78-2-osmc

Thank you!

Nacho

**Comment by Stephane-Peel** [comment]
Currently trying to compile and install this driver on a **RPI4 running OSMC** ...

In my case i guess i need to use the **rbp464-headers-5.10.78-5-osmc**

But make fail with this error : 

```
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.78-5-osmc/build M=/usr/src/RTL8812BU_for_Raspbian  modules
make[1]: Entering directory '/usr/src/rbp464-headers-5.10.78-5-osmc'
  CC [M]  /usr/src/RTL8812BU_for_Raspbian/core/rtw_cmd.o
In file included from ./include/asm-generic/int-ll64.h:11,
                 from ./arch/arm/include/uapi/asm/types.h:5,
                 from ./include/uapi/linux/types.h:5,
                 from ./include/linux/types.h:6,
                 from /usr/src/RTL8812BU_for_Raspbian/include/basic_types.h:75,
                 from /usr/src/RTL8812BU_for_Raspbian/include/drv_types.h:26,
                 from /usr/src/RTL8812BU_for_Raspbian/core/rtw_cmd.c:17:
./include/uapi/asm-generic/int-ll64.h:12:10: fatal error: asm/bitsperlong.h: No such file or directory
 #include <asm/bitsperlong.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:280: /usr/src/RTL8812BU_for_Raspbian/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1825: /usr/src/RTL8812BU_for_Raspbian] Error 2
make[1]: Leaving directory '/usr/src/rbp464-headers-5.10.78-5-osmc'
make: *** [Makefile:2284: modules] Error 2

```

Tried to compile using **rbp2-headers-5.10.78-5-osmc**.
It went fine but obviously (for me) the driver will not install 

```
 sudo modprobe 88x2bu
modprobe: ERROR: could not insert '88x2bu': Exec format error
```

If someone could help me with this it will be really great !

**Comment by xnosek00** [comment]
Hi @Stephane-Peel, 

  I have the same problem with different wifi drivers: https://github.com/morrownr/8814au/issues/72

  Really the same error output - asm/bitsperlong.h - no such file or directory.

  I thought, that rbp2-headers will be solution, but the same problem with inserting compiled module. 

  But it looks like, that is possible to compile drivers on Raspberry debian distributions - you can see list of tested distribution: https://github.com/morrownr/8812au-20210629

  So I think, there  is something different on OSMC. I'm trying to investigate what is different and why we can not compile drivers.
