### ISSUE TITLE
Does not compile on Linux raspberrypi 5.15.32-v7l+  // net/ipx.h is flagged as not found

### ISSUE THREAD

**Issue by dirbasti** [fastoe/RTL8812BU_for_Raspbian#19]
###Does not compile on Linux raspberrypi 5.15.32-v7l+  // net/ipx.h is flagged as not found

Error message: 
./include/net/inet_connection_sock.h: In function ‘inet_csk_reqsk_queue_is_full’:
./include/net/inet_connection_sock.h:282:38: warning: comparison of integer expressions of different signedness: ‘int’ and ‘u32’ {aka ‘const unsigned int’} [-Wsign-compare]
  282 |  return inet_csk_reqsk_queue_len(sk) >= sk->sk_max_ack_backlog;
      |                                      ^~
/home/user/RTL8812BU_for_Raspbian/core/rtw_br_ext.c: At top level:
/home/user/RTL8812BU_for_Raspbian/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h: Datei oder Verzeichnis nicht gefunden
   20 |  #include <net/ipx.h>

Kernel used:
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

branch 5.6.1 and 5.8.7 were tested, please advice.

**Comment by dheeraj-rn** [comment]
Check if #14 works or not. You may want to get the code from [here](https://github.com/cmurken/RTL8812BU_for_Raspbian/tree/v5.6.1).
